### ISSUE TITLE
[Bug report] 首次运行pnpm run serve出错

### ISSUE THREAD

**Issue by AisonSu** [didi/mpx#1413]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
问题触发的条件：创建微信小程序，非跨平台，无需ssr，需要云开发，需要typescript，需要原子类，需要单元化测试，需要自动化测试，必现
2. 期望的表现：
正常编译
3. 实际的表现
报错
![微信截图_20240225111039](https://github.com/didi/mpx/assets/42713977/d7b76fc6-2f05-4dc9-849f-5b5ae870a197)
**环境信息描述**  
至少包含以下部分：
1. 系统类型：Windows
2. Mpx依赖版本
```
dependencies:
  '@mpxjs/api-proxy':
    specifier: ^2.9.0
    version: 2.9.19
  '@mpxjs/core':
    specifier: ^2.9.0
    version: 2.9.17(@mpxjs/api-proxy@2.9.19)(@mpxjs/store@2.9.9)(vue-demi@0.14.7)(vue-i18n-bridge@9.9.1)(vue-i18n@8.28.2)(vue@2.7.16)
  '@mpxjs/fetch':
    specifier: ^2.9.0
    version: 2.9.1
  '@mpxjs/pinia':
    specifier: ^2.9.0
    version: 2.9.1(@mpxjs/core@2.9.17)(pinia@2.1.7)(vue-demi@0.14.7)(vue@2.7.16)
  '@mpxjs/store':
    specifier: ^2.9.0
    version: 2.9.9(@mpxjs/core@2.9.17)
  '@mpxjs/utils':
    specifier: ^2.9.0
    version: 2.9.1(@mpxjs/core@2.9.17)
  pinia:
    specifier: ^2.0.14
    version: 2.1.7(typescript@4.9.5)(vue@2.7.16)
  vue:
    specifier: ^2.7.0
    version: 2.7.16
  vue-demi:
    specifier: ^0.14.6
    version: 0.14.7(vue@2.7.16)
  vue-i18n:
    specifier: ^8.27.2
    version: 8.28.2(vue@2.7.16)
  vue-i18n-bridge:
    specifier: ^9.2.2
    version: 9.9.1(vue@2.7.16)
  vue-router:
    specifier: ^3.1.3
    version: 3.6.5(vue@2.7.16)

devDependencies:
  '@babel/core':
    specifier: ^7.10.4
    version: 7.23.9
  '@babel/plugin-transform-runtime':
    specifier: ^7.10.4
    version: 7.23.9(@babel/core@7.23.9)
  '@babel/preset-env':
    specifier: ^7.10.4
    version: 7.23.9(@babel/core@7.23.9)
  '@babel/runtime-corejs3':
    specifier: ^7.10.4
    version: 7.23.9
  '@mpxjs/babel-plugin-inject-page-events':
    specifier: ^2.9.0
    version: 2.9.5
  '@mpxjs/eslint-config-ts':
    specifier: ^1.0.5
    version: 1.0.10(eslint@7.32.0)(typescript@4.9.5)
  '@mpxjs/miniprogram-simulate':
    specifier: ^1.4.17
    version: 1.4.17
  '@mpxjs/mpx-cli-service':
    specifier: ^2.0.0
    version: 2.1.7(stylus-loader@6.2.0)(vue@2.7.16)
  '@mpxjs/mpx-jest':
    specifier: ^0.0.24
    version: 0.0.24(@mpxjs/webpack-plugin@2.9.18)
  '@mpxjs/size-report':
    specifier: ^2.9.0
    version: 2.9.14(@mpxjs/webpack-plugin@2.9.18)
  '@mpxjs/unocss-base':
    specifier: ^2.9.0
    version: 2.9.7
  '@mpxjs/unocss-plugin':
    specifier: ^2.9.0
    version: 2.9.17(@mpxjs/webpack-plugin@2.9.18)(postcss@8.4.35)(vite@4.5.2)(webpack@5.90.3)
  '@mpxjs/vue-cli-plugin-mpx':
    specifier: ^2.0.0
    version: 2.1.7(@babel/core@7.23.9)(@mpxjs/webpack-plugin@2.9.18)(css-loader@6.10.0)(stylus-loader@6.2.0)(webpack@5.90.3)
  '@mpxjs/vue-cli-plugin-mpx-cloud-func':
    specifier: ^2.0.0
    version: 2.1.7(webpack@5.90.3)
  '@mpxjs/vue-cli-plugin-mpx-e2e-test':
    specifier: ^2.0.0
    version: 2.1.7
  '@mpxjs/vue-cli-plugin-mpx-eslint':
    specifier: ^2.0.0
    version: 2.1.7(eslint@7.32.0)(webpack@5.90.3)
  '@mpxjs/vue-cli-plugin-mpx-typescript':
    specifier: ^2.0.0
    version: 2.1.7(typescript@4.9.5)(webpack@5.90.3)
  '@mpxjs/vue-cli-plugin-mpx-unit-test':
    specifier: ^2.0.0
    version: 2.1.7(@babel/core@7.23.9)
  '@mpxjs/vue-cli-plugin-mpx-utility-first-css':
    specifier: ^2.0.0
    version: 2.1.7
  '@mpxjs/webpack-plugin':
    specifier: ^2.9.0
    version: 2.9.18(webpack@5.90.3)
  '@types/jest':
    specifier: ^27.5.1
    version: 27.5.2
  '@vue/cli-service':
    specifier: ~5.0.0
    version: 5.0.8(stylus-loader@6.2.0)(vue@2.7.16)
  autoprefixer:
    specifier: ^10.2.4
    version: 10.4.17(postcss@8.4.35)
  babel-jest:
    specifier: ^27.4.5
    version: 27.5.1(@babel/core@7.23.9)
  eslint:
    specifier: ^7.0.0
    version: 7.32.0
  jest:
    specifier: ^27.4.5
    version: 27.5.1
  postcss:
    specifier: ^8.2.6
    version: 8.4.35
  stylus:
    specifier: ^0.55.0
    version: 0.55.0
  stylus-loader:
    specifier: ^6.1.0
    version: 6.2.0(stylus@0.55.0)(webpack@5.90.3)
  ts-jest:
    specifier: ^27.1.2
    version: 27.1.5(@babel/core@7.23.9)(@types/jest@27.5.2)(babel-jest@27.5.1)(jest@27.5.1)(typescript@4.9.5)
  typescript:
    specifier: ^4.1.3
    version: 4.9.5
  webpack:
    specifier: ^5.43.0
    version: 5.90.3
```
**目前尝试过的解决办法**
修改`/node_modules/.pnpm/@mpxjs+api-proxy@2.9.19/node_modules/@mpxjs/api-proxy/src/platform/index.js`中112行`export * from './api/event-channel/'`为`export * from './api/event-channel/index.web'`，可以正常运行
