### ISSUE TITLE
[Bug report] style scoped page选择器能否过滤

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#536]
**问题描述**  
使用autoScopeRules时如果页面文件中包含页面，支付宝下页面中含有page选择器会也会加上scopedId，导致page选择器无效，scoped这里可以针对page选择器进行过滤吗？

**环境信息描述**  
Mac
mpx版本
"@mpxjs/core": "^2.5.33"
"@mpxjs/webpack-plugin": "^2.5.33"
支付宝IDE 1.13.4

**最简复现demo**  

```javascript
// mpx.webpack.conf.js
{
    autoScopeRules: {
        include: [resolve('src')],
        exclude: [
            resolve('src/app.mpx'),
            resolve('src/assets'),
            resolve('src/components/@vant'),
        ],
    },
}
```

```css
// src/pages/xxx.mpx

page {
    background-color: #f8f8f8
}

// 编译后

page.m9ed7a486 {
    background-color: #f8f8f8;
}
```
